extracted_features:
  - OverallQual
  - GrLivArea
  - GarageArea
  - TotalBsmtSF
  # Added for getting normality
  - HasGarage
  - HasBsmt
col_id_name: Id
col_target_name: SalePrice
dropped_ids:
  - 524
  - 1299
# Reference: https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
lgbm_params:
  instance:
    random_state: 0
    silent: True
  candidates:
    boosting_type: [gbdt]
    learning_rate: {low: 0.1, high: 0.1, step: 0.1}
    lambda_l1: {low: 0.1, high: 1.0, step: 0.1}
    lambda_l2: {low: 0, high: 0, step: 0.1}
  fit:
    categorical_feature:
      - HasGarage
      - HasBsmt
cv:
  n_folds: 10
