extracted_features:
  - OverallQual
  - GrLivArea
  - GarageArea
  - TotalBsmtSF
  # Added for getting normality
  - HasGarage
  - HasBsmt
col_id_name: Id
col_target_name: SalePrice
dropped_ids:
  - 524
  - 1299
# Reference: https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
lgbm_params:
  instance:
    boosting_type: gbdt
    learning_rate: 0.1
    reg_alpha: 0
    reg_lambda: 0
    random_state: 0
    silent: True
  fit:
    categorical_feature:
      - HasGarage
      - HasBsmt
cv:
  n_folds: 10
