extracted_features:
  - OverallQual
  - GrLivArea
  - GarageArea
  - TotalBsmtSF
  # Added for getting normality
  - HasGarage
  - HasBsmt
col_id_name: Id
col_target_name: SalePrice
dropped_ids:
  - 524
  - 1299
# Reference: https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
lgbm_params:
  max_bin: 100
  learning_rate: 0.1
  num_itarations: 100
  num_leaves: 31
  boosting: dart
  objective: regression
  metric: rmse
  lambda_l1: 0
  lambda_l2: 0
  verbosity: -1

# # For debugging(faster speed)
# lgbm_params:
#   max_bin: 100
#   learning_rate: 0.1
#   num_itarations: 100
#   num_leaves: 31
#   boosting: dart
#   objective: regression
#   metric: rmse
#   lambda_l1: 0
#   lambda_l2: 0
#   verbosity: -1
  