# Features
extracted_features:
  - OverallQual
  - GrLivArea
  - GarageArea
  - TotalBsmtSF
  # Added for getting normality
  - HasGarage
  - HasBsmt
col_id_name: Id
col_target_name: SalePrice
dropped_ids:
  - 524
  - 1299
random_state: 0
# Hyper parameters
# Reference: https://lightgbm.readthedocs.io/en/latest/Parameters-Tuning.html
params:
  lasso:
    candidates:
      alpha: {low: 1.0e-4, high: 1.0e-1}  # loguniform
  enet:
    candidates:
      alpha: {low: 1.0e-4, high: 1.0e-3}  # loguniform
      l1_ratio: {low: 0.1, high: 0.9, step: 0.1}  # float
  lgbm:
    instance:
      silent: True
    candidates:
      boosting_type: [gbdt]
      learning_rate: {low: 1.0e-4, high: 1.0e-1}  # loguniform
      lambda_l1: {low: 0.1, high: 1.0, step: 0.1}  # float
      lambda_l2: {low: 0, high: 0, step: 0.1}  # float
    fit:
      categorical_feature:
        - HasGarage
        - HasBsmt
cv:
  # Don't use `learning_curve()`, try following numbers by hand.
  # n_folds: 3
  # n_folds: 5
  n_folds: 10
